## Why using Numpy if we have python lists ?
NumPy is more fast than python list because is store just the binary form of the number instead the in list we store many other information related to the behivior of python objects.

also in numpy we don't check the type of the variable each time we hava one fixed type (less work ==> more performance)

also in numpy for when we create an array we allow for it a continus space memry each element is in the next of the other element. But in the python list we don't have a coninus memory.

also we can do more with numpy!!!.

all resourses for this courses are quoted from the official numpy documentation https://numpy.org/doc/

## Load NumPy 

In [1]:
import numpy as np

## The Basics

In [2]:

a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:

b = np.array([[9,8,7,5,5,4,3],[9,7,0,1,5,9,0]])
b

array([[9, 8, 7, 5, 5, 4, 3],
       [9, 7, 0, 1, 5, 9, 0]])

In [4]:
# get dimention
print(b.ndim)
print(a.ndim)

2
1


In [5]:
# get Shape
print(b.shape)
print(a.shape)

(2, 7)
(3,)


In [6]:
# get type
print(a.dtype)

int32


In [7]:
# get size
print(a.itemsize)

4


In [8]:
# total size
print(a.size*a.itemsize)
a.nbytes

12


12

you can specified your data to be more efficient with adding 
some proprieteis to the array dtype

In [9]:
a = np.array([[1,2,3],[1,2,3]],dtype = 'int16')
print(a.dtype)
print(a,'\n',a.nbytes)


int16
[[1 2 3]
 [1 2 3]] 
 12


**Access to element**

In [10]:
a = np.array([[0,8,7,5,5,4,3],
              [1,7,0,1,5,9,0],
              [2,8,7,5,5,4,3],
              [3,7,0,1,5,9,0]])
a

array([[0, 8, 7, 5, 5, 4, 3],
       [1, 7, 0, 1, 5, 9, 0],
       [2, 8, 7, 5, 5, 4, 3],
       [3, 7, 0, 1, 5, 9, 0]])

In [11]:
# get a specific element :
print(a[1][5]) # way 1
print(a[1,5])  # way 2

9
9


In [12]:
# get a specific row
print(a[0,:])
# get a specific column
print(a[:,2])

[0 8 7 5 5 4 3]
[7 0 7 0]


In [13]:
# get a specific values : [start_index , end_index , step_to_take]:
print(a[0,1:5:2])
print(a[0:3:2,0])
print(a[0,1:-2:2])

[8 5]
[0 2]
[8 5]


In [14]:
# change a specific value in array
a[1,3]= 9999
a

array([[   0,    8,    7,    5,    5,    4,    3],
       [   1,    7,    0, 9999,    5,    9,    0],
       [   2,    8,    7,    5,    5,    4,    3],
       [   3,    7,    0,    1,    5,    9,    0]])

Theirs a banch of thing that u can do with indexes now you have the assencial try to applayn it in 3d exemples (tensors), but you dont really need it for beginer problems.

 ### initializing Different Types of Arrays

In [15]:
# Zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
# ones Matrix / specifing the tye is opional
np.ones((2,3),dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [17]:
# chose a specifing number to initialize a matrix :
np.full((2,2),999)

array([[999, 999],
       [999, 999]])

In [18]:
# full like method :
'''                  is used to create a matrix with a unifie number 
 but with a size of an other matrix already exist. '''
print('a =')
print(a)
print('\nfull_like(a,1234) =  ')
print(np.full_like(a,1234))

a =
[[   0    8    7    5    5    4    3]
 [   1    7    0 9999    5    9    0]
 [   2    8    7    5    5    4    3]
 [   3    7    0    1    5    9    0]]

full_like(a,1234) =  
[[1234 1234 1234 1234 1234 1234 1234]
 [1234 1234 1234 1234 1234 1234 1234]
 [1234 1234 1234 1234 1234 1234 1234]
 [1234 1234 1234 1234 1234 1234 1234]]


**INITIALIZE WITH A RANDOM NUMBER :**

In [19]:
# randm values betwen 0 and 1 dicimal
np.random.rand(4,2)

array([[0.88372322, 0.86897966],
       [0.46497273, 0.45664644],
       [0.02776845, 0.91500839],
       [0.62730686, 0.65206559]])

In [20]:
# random integer value
np.random.randint(7)

3

In [21]:
# random matrix of int
np.random.randint(10,size=(3,3))

array([[5, 6, 4],
       [9, 3, 2],
       [8, 3, 4]])

In [22]:
# identity matrix:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# repeat an array :
arr = np.array([[1,2,3]])
print(arr)
r1 = np.repeat(arr ,3 ,axis=0)
r1

[[1 2 3]]


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

**Be careful with copying matrix in numpy !!**

In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A = \n',a)
b = a
print('B = \n',b)
b[0] = 100
print('B = \n',b)
print('A = \n',a)
print('>> why A also changed  ? ...')
print('>>>> because you don\'t make a copy to make a copy we just tell \nnumpy to make a = b is not the same thing.')

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
 [[100 100 100]
 [  4   5   6]
 [  7   8   9]]
A = 
 [[100 100 100]
 [  4   5   6]
 [  7   8   9]]
>> why A also changed  ? ...
>>>> because you don't make a copy to make a copy we just tell 
numpy to make a = b is not the same thing.


**To make a copy follow those instraction :**

In [25]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A = \n',a)
b = a.copy()       # copy with the copy method
print('B = \n',b)
b[0] = 100
print('B = \n',b)
print('A = \n',a)
print('\n>> yahooo evry thing is fine (; ')

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
 [[100 100 100]
 [  4   5   6]
 [  7   8   9]]
A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

>> yahooo evry thing is fine (; 


### NumPy operatio 
just like the array operations . 

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
a+2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [31]:
a*2 #scaler multiplication

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [32]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [33]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [34]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

## Liniar Algebra

In [35]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

 **NOW WE WANNA TO CALCULATE AB OR A x B :**

In [41]:
print('A = \n',a)
print('\nB = \n',b)
print('\nAB = ')
print(np.matmul(a,b))

A = 
 [[1. 1. 1.]
 [1. 1. 1.]]

B = 
 [[2 2]
 [2 2]
 [2 2]]

AB = 
[[6. 6.]
 [6. 6.]]


### find determinant 

In [43]:
# find determinant 
c=np.matmul(a,b)
np.linalg.det(c)

0.0

In [44]:
c=np.identity(3)
np.linalg.det(c)

1.0

In [52]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A = \n',a)
b = np.array([0,0,0])
print('\nB = \n',b)

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B = 
 [0 0 0]


In [54]:
#solve the liniar system
np.linalg.solve(a, b)

array([ 0.,  0., -0.])

In [57]:
# calculate the inverses
print(np.linalg.inv(a))
np.linalg.inv(c) #c is the identety matrix we define earlyer

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 for more about liniar algebra in numpy vist : https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

## Statistics :

In [58]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.min(stats)


1

In [60]:
np.max(stats, axis=1)


array([3, 6])

In [61]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [63]:

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print('\n',after)
after = before.reshape((2,2,2))
print('\n',after)
after = before.reshape((4,2))
print('\n',after)

[[1 2 3 4]
 [5 6 7 8]]

 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Boolean Masking and Advanced Indexing

In [71]:
a = np.random.randint(100,size=(5,5))
a

array([[67, 86, 54, 13, 57],
       [40,  2, 73, 98, 16],
       [93, 33, 80, 80, 39],
       [76, 15, 30, 71, 85],
       [89, 94, 66, 69, 72]])

In [72]:
a > 50

array([[ True,  True,  True, False,  True],
       [False, False,  True,  True, False],
       [ True, False,  True,  True, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

thanks for